
//2 icons directly installed to res/image
#define ICON_DIRECTORY      RESDIR"/images/music_player"
#define COVERFLOW_IMAGE_DIR "Cover_flow"
#define STORAGE_TYPE_DIR	"storage_type"

#define DEFAULT_THUMBNAIL   			ICON_DIRECTORY"/34_thumb_07.png"
#define DEFAULT_THUMBNAIL_FOLDER        ICON_DIRECTORY"/default_folder.png"

#define THUMBNAIL_MOST_PLAYED   	ICON_DIRECTORY"/34_mostplayed.png"
#define THUMBNAIL_RECENTLY_PLAYED   ICON_DIRECTORY"/34_recentlyplayed.png"
#define THUMBNAIL_RECENTLY_ADDED   	ICON_DIRECTORY"/34_recentlyadded.png"
#define THUMBNAIL_QUICK_LIST   		ICON_DIRECTORY"/34_quicklist.png"
#define THUMBNAIL_PLAYLIST          		ICON_DIRECTORY"/34_playlist.png"
#define THUMBNAIL_PLAYLIST_NOITEM   	ICON_DIRECTORY"/34_player_list_thum_noitems.png"

#define MP_CTRBAR_ICON_SONGS		ICON_DIRECTORY"/T02_controlbar_icon_all.png"
#define MP_CTRBAR_ICON_PLAYLIST	ICON_DIRECTORY"/T02_controlbar_icon_playlists.png"
#define MP_CTRBAR_ICON_ALBUM		ICON_DIRECTORY"/T02_controlbar_icon_music_albums.png"
#define MP_CTRBAR_ICON_ARTIST		ICON_DIRECTORY"/T02_controlbar_icon_artist.png"
#define MP_CTRBAR_ICON_GENRE		ICON_DIRECTORY"/T02_controlbar_icon_genres.png"
#define MP_CTRBAR_ICON_YEAR		ICON_DIRECTORY"/T02_controlbar_icon_years.png"
#define MP_CTRBAR_ICON_COMPOSER	ICON_DIRECTORY"/T02_controlbar_icon_composer.png"
#define MP_CTRBAR_ICON_FOLDER		ICON_DIRECTORY"/T02_controlbar_icon_folders.png"
#define MP_CTRBAR_ICON_SQUARE		ICON_DIRECTORY"/T02_controlbar_icon_music_square.png"
#define MP_ICON_EDIT				ICON_DIRECTORY"/T02_controlbar_icon_edit.png"
#define MP_ICON_SEARCH			ICON_DIRECTORY"/T02_controlbar_icon_search.png"
#define MP_ICON_CANCEL			ICON_DIRECTORY"/T02_controlbar_icon_cancel.png"
#define MP_ICON_SHARE			ICON_DIRECTORY"/T02_controlbar_icon_share.png"
#define MP_ICON_DELETE			ICON_DIRECTORY"/T02_controlbar_icon_delete.png"
#define MP_ICON_ADD_TO_PLST	ICON_DIRECTORY"/T02_controlbar_icon_add_to_playlist.png"
#define MP_ICON_NEW				ICON_DIRECTORY"/T02_controlbar_icon_add.png"
#define MP_ICON_ALL_SHARE		ICON_DIRECTORY"/T02_controlbar_icon_nearby_device.png"
#define MP_ICON_ALLSHARE_FOLDER	ICON_DIRECTORY"/allshare/myfile_icon_folder.png"
#define MP_ICON_SYNC_START		ICON_DIRECTORY"/02_controlbar_icon_synchronise_start_sync.png"
#define MP_SQUARE_ICON_BACK_BUTTON ICON_DIRECTORY"/00_winset_Back.png"

#define DALI_IMAGE_DIR  			ICON_DIRECTORY"/3d_picture"
#define DALI_IMAGE_BACKGROUD_BG   DALI_IMAGE_DIR"/T02_cover_flow_bg.png"
#define DALI_IMAGE_SHADOW_BG    ICON_DIRECTORY"/T02_music_player_image_shadow.png"

//2  icons included in edj file
#define MP_ICON_COVERFLOW_BG 				COVERFLOW_IMAGE_DIR"/T02_cover_flow_bg.png"
#define MP_ICON_COVERFLOW_SHADOW_BG		COVERFLOW_IMAGE_DIR"/T02_cover_flow_album_shadow_bg.png"
#define MP_ICON_STORAGE_PHONE				STORAGE_TYPE_DIR"/T02_phone_02.png"
#define MP_ICON_STORAGE_MEMORY				STORAGE_TYPE_DIR"/T02_memory_card_02.png"
#define MP_ICON_STORAGE_EXTERNAL			STORAGE_TYPE_DIR"/T02_external_storage_02.png"
#define MP_ICON_SQUARE_CELL_SELECTED 		"T02_square_cell_press.png"
#define MP_ICON_VOLUME_MIN			"T02_volume_icon_01.png"
#define MP_ICON_VOLUME_MAX			"T02_volume_icon_02.png"
#define MP_ICON_SOUND_PATH			"T02_icon_soundPath.png"
#define MP_ICON_NEARBY_DMR			"T02_title_icon_nearby_device.png"
#define MP_ICON_MINI_PLAYER			"mini_app/T02_control_icon_apps.png"
#define MP_ICON_VIDEO_PLAY			"T02_Video_play.png"

